apiVersion: v1
name: devops
version: 0.3.0
displayName:
  zh: DevOps
  en: DevOps
description:
  zh: KubeSphere DevOps 提供端到端的工作流，集成主流 CI/CD 工具，帮助不同的组织加快产品上市时间。
  en: KubeSphere DevOps offers an end-to-end workflow, integrating mainstream CI/CD tools, and helps organizations accelerate the time to market for products.
keywords:
  - DevOps
  - CI/CD
  - Integration & Delivery
home: https://www.kubesphere.io/devops/
category: integration-delivery
sources:
  - https://github.com/kubesphere/ks-devops
  - https://github.com/kubesphere-sigs/ks-devops-helm-chart
kubeVersion: ">=1.19.0"
ksVersion: ">=4.0.0-beta"
provider:
  en:
    name: "QingCloud Technologies"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.io"
  zh:
    name: "北京青云科技股份有限公司"
    email: "kubesphere@yunify.com"
    url: "https://kubesphere.com.cn"
maintainers:
  - name: jackyu
    email: jackyu@yunify.com
  - name: yazhouhu
    email: yazhouhu@yunify.com
staticFileDirectory: static
icon: ./static/devops-icon.png
screenshots:
  - https://ks-extension-staging.pek3b.qingstor.com/devops/0.3.0/devops-screenshot-0.png
  - https://ks-extension-staging.pek3b.qingstor.com/devops/0.3.0/devops-screenshot-1.png
  - https://ks-extension-staging.pek3b.qingstor.com/devops/0.3.0/devops-screenshot-2.png
  - https://ks-extension-staging.pek3b.qingstor.com/devops/0.3.0/devops-screenshot-3.png
  - https://ks-extension-staging.pek3b.qingstor.com/devops/0.3.0/devops-screenshot-4.png
installationMode: Multicluster
dependencies:
  - name: extension
    tags:
      - extension
  - name: agent
    tags:
      - agent