apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dmp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dmp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dmp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dmp.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/dmp/dmp-server" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DSN
              value: {{ include "postgresql.dns" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


